version: '3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./conf/custom_mysql.cnf:/etc/mysql/conf.d/custom_mysql.cnf
      - ./conf/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  
  db_admin:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.16.1
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/error.log:/etc/nginx/error.log
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
      - 4003:4003
      - 4004:4004
    depends_on:
      - issuer
      - id_verifier
      - ledger
      - website
      - sign_verifier

  issuer:
    image: iesiyok/trollthrottle:issuer
    volumes:
      - ./conf/database.yml:/issuer/config/database.yml
      - ./conf/issuer_unicorn.rb:/issuer/config/unicorn.rb
      - ./conf/issuer_startup.sh:/issuer/startup.sh
      - ./conf/wait-for-services.sh:/issuer/wait-for-services.sh
      - ./logs/issuer/unicorn.stderr.log:/issuer/log/unicorn.stderr.log
      - ./logs/issuer/unicorn.stdout.log:/issuer/log/unicorn.stdout.log
      - ./keys_and_certs:/issuer/keys_and_certs
      - ./logs/issuer:/issuer/log
    ports:
      - 3000:3000
    depends_on:
      - db

  id_verifier:
    image: iesiyok/trollthrottle:id_verifier
    volumes:
      - ./conf/database.yml:/id_verifier/config/database.yml
      - ./conf/id_verifier_unicorn.rb:/id_verifier/config/unicorn.rb
      - ./conf/id_verifier_startup.sh:/id_verifier/startup.sh
      - ./conf/wait-for-services.sh:/id_verifier/wait-for-services.sh
      - ./logs/id_verifier/unicorn.stderr.log:/id_verifier/log/unicorn.stderr.log
      - ./logs/id_verifier/unicorn.stdout.log:/id_verifier/log/unicorn.stdout.log
      - ./keys_and_certs:/id_verifier/keys_and_certs
      - ./logs/id_verifier:/id_verifier/log
    ports:
      - 3001:3001
    depends_on:
      - db  
      - issuer 

  ledger:
    image: iesiyok/trollthrottle:ledger
    volumes:
      - ./conf/database.yml:/ledger/config/database.yml
      - ./conf/ledger_unicorn.rb:/ledger/config/unicorn.rb
      - ./conf/ledger_startup.sh:/ledger/startup.sh
      - ./conf/wait-for-services.sh:/ledger/wait-for-services.sh
      - ./logs/ledger/unicorn.stderr.log:/ledger/log/unicorn.stderr.log
      - ./logs/ledger/unicorn.stdout.log:/ledger/log/unicorn.stdout.log
      - ./logs/ledger:/ledger/log
    ports:
      - 3002:3002
    depends_on:
      - db
      - issuer

  website:
    image: iesiyok/trollthrottle:website
    volumes:
      - ./conf/database.yml:/website/config/database.yml
      - ./conf/website_unicorn.rb:/website/config/unicorn.rb
      - ./conf/website_startup.sh:/website/startup.sh
      - ./conf/wait-for-services.sh:/website/wait-for-services.sh
      - ./logs/website/unicorn.stderr.log:/website/log/unicorn.stderr.log
      - ./logs/website/unicorn.stdout.log:/website/log/unicorn.stdout.log
      - ./logs/website:/website/log
    ports:
      - 3003:3003
    depends_on:
      - db
      - issuer
    
  sign_verifier:
    image: iesiyok/trollthrottle:sign_verifier
    volumes:
      - ./conf/database.yml:/sign_verifier/config/database.yml
      - ./conf/sign_verifier_unicorn.rb:/sign_verifier/config/unicorn.rb
      - ./conf/sign_verifier_startup.sh:/sign_verifier/startup.sh
      - ./conf/wait-for-services.sh:/sign_verifier/wait-for-services.sh
      - ./logs/sign_verifier/unicorn.stderr.log:/sign_verifier/log/unicorn.stderr.log
      - ./logs/sign_verifier/unicorn.stdout.log:/sign_verifier/log/unicorn.stdout.log
      - ./keys_and_certs:/sign_verifier/keys_and_certs
      - ./logs/sign_verifier:/sign_verifier/log
    ports:
      - 3004:3004
    depends_on:
      - db
      - issuer

  simulator:
    image: iesiyok/trollthrottle:simulator
    volumes:
      - ./conf/locals.js:/simulator/locals.js
      - ./data:/simulator/data
      - ./keys_and_certs:/sign_verifier/keys_and_certs
    depends_on:
      - db
      - nginx
    environment:
      - TZ=Europe/Berlin
    
